feat: add concept of wiki
officelifehq/officelife pull request #1129
Opened 2021-06-21 22:08 UTC by djaiss

Close #917

This PR adds the notion of wiki.
A company can have as many wikis as it wants. A wiki is made of pages.
Pages have page revisions, so we know who did what.

2021-06-25 18:22 UTC, cweagans commented
I have nothing to add to this PR from a code perspective at present, but I just want to say how impressed I am at your development speed. Going from zero to this PR in the span of a few days is pretty amazing :)

2021-06-26 01:53 UTC, djaiss commented
> I have nothing to add to this PR from a code perspective at present, but I just want to say how impressed I am at your development speed. Going from zero to this PR in the span of a few days is pretty amazing :)

Thanks @cweagans! Well, it's only a first iteration, with basic features! We can do a gazillion other things with the wiki!

2021-06-27 18:04 UTC, djaiss commented
Only the documentation remains to be written for this PR.

There are a lot of features we can do with wikis but this is the bare minimum we should do here to support this feature.

2021-06-30 20:46 UTC, asbiin requested changes
Such a big PR! Great work!

2021-06-30 20:46 UTC, asbiin commented on resources/js/Pages/Company/KB/Create.vue
> +                        :maxlength="191"
This limit should come from database instead of hard-coded here

2021-06-30 20:46 UTC, asbiin commented on resources/js/Pages/Company/KB/Index.vue
> +                    {{ $t('kb.index_number_pages', {count: wiki.count}) }}
It should be
```suggestion
                    {{ $tc('kb.index_number_pages', wiki.count, {count: wiki.count}) }}
```

2021-06-30 20:46 UTC, asbiin commented on resources/lang/en/kb.php
> +    'index_number_pages' => '{count} pages',
It should be
```suggestion
    'index_number_pages' => '{count} page|{count} pages',
```

2021-07-04 02:05 UTC, merged