feat: add demo mode to instance
officelifehq/officelife pull request #897
Opened 2021-05-24 02:41 UTC by djaiss

This PR adds a demo mode to OfficeLife.

The demo mode is made for an instance that is supposed to showcase how OfficeLife behaves with real data.

To enable the demo mode, we need to edit a new .env variable called `DEMO_MODE`. By default, the demo mode is set to false.

Once the demo mode is enabled:

- a new banner will be added to the header of the application, indicating that the instance runs on the demo mode,
- some features are deactivated: importing users, adding new users, deleting the account and deleting employees.

![image](https://user-images.githubusercontent.com/61099/119289150-05f34c80-bc18-11eb-993f-f741c2d493b4.png)

2021-05-24 02:41 UTC, djaiss commented
@asbiin could you review?

2021-05-24 02:45 UTC, djaiss commented
@asbiin wait, don't review now. Still have changes to do.

2021-05-24 03:01 UTC, djaiss commented
@asbiin that should be good.

2021-05-25 14:37 UTC, asbiin requested changes
Nice feature!
You deactivated some actions for demo mode at View level. But you also have to check it in the Controller, or someone would be able to forge a request and run it!

2021-05-25 14:37 UTC, asbiin commented on app/Http/Controllers/Auth/RegisterController.php
> +            return redirect('/login');
```suggestion
            return redirect()->route('login');
```

2021-05-25 14:46 UTC, djaiss commented
>  You deactivated some actions for demo mode at View level. But you also have to check it in the Controller, or someone would be able to forge a request and run it!

You are right. I'll add those changes.

2021-05-25 22:24 UTC, merged